# ATOC5860 - some python gotchas - Lecture #1
##### Prof. Kay (CU)
##### Last updated: January 13, 2023

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd  # library for data analysis for text files (everything but netcdf files)
%matplotlib inline 

In [2]:
## python gotcha #1 -- indexing
foo=np.linspace(0,10,11)
print(foo)
print(foo.shape)

## python is 0 based
print(foo[0])

## indexing over the first 5 values of an array only selects the first 4 values of an array
print(foo[0:4])

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
(11,)
0.0
[0. 1. 2. 3.]


In [3]:
## python gotcha #2 -- copying vs. linking arrays

## if you want to copy an array
foo_new = foo.copy() 

## if you want to link an array
foo_new_linked = foo

foo[0]=10
print(foo)
print(foo_new)
print(foo_new_linked)

[10.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[10.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [4]:
## python slick combining text and numbers (Thanks Devon Dunmire (CU))

print(f'this is {foo}')
print('this is {foo}')

this is [10.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
this is {foo}


## Do you have a python gotcha to add?  Send it to Professor Kay :)

### code that hides code - Neat to have as an option if you don't want to show the code...

In [1]:
#from IPython.display import HTML
#HTML('''<script>
#code_show=true; 
#function code_toggle() {
# if (code_show){
# $('div.input').hide();
# } else {
# $('div.input').show();
# }
# code_show = !code_show
#} 
#$( document ).ready(code_toggle);
#</script>
#The raw code for this IPython notebook is by default hidden for easier reading.
#To toggle on/off the raw code, click <a href="javascript:code_toggle()">here</a>.''')